### ISSUE TITLE
Search returns k*#partitions

### ISSUE THREAD

**Issue by eli-shapira** [argmaxml/vecsim#2]
When using `SciKitIndex` to find similarities, and there are partitions added, it returns by search k * number of partitions if not search for specific partition.
Similar problem (in similar conditions), you cannot ask for k larger than the smallest partition.

Sample code (taken from the README, with a little change in the number of users):
```python
sim = SciKitIndex(metric='cosine', dim=32)
user_ids = ["user_"+str(1+i) for i in range(10)]
user_data = np.random.random((10,32))
item_ids=["item_"+str(101+i) for i in range(100)]
item_data = np.random.random((100,32))
sim.add_items(user_data, user_ids, partition="users")
sim.add_items(item_data, item_ids, partition="items")
sim.init()
query = np.random.random(32)
```
Running
```python
dists, items = sim.search(query, k=10)
print(len(dists))
```
will results  `20`
and `dists, items = sim.search(query, k=12)` will result in an Error.

The problem is that in the `BaseIndex.search` it searches for k for every partition.  

https://github.com/argmaxml/vecsim/blob/96b9a428f4aaad4e24714c98b0ab7873c9c81bca/vecsim/similarity_helpers.py#L84-L92

Suggest correction is
```python
 else:
     scores, names = [], []
     for p in self.indices:
     scores_p, idx_p = self.indices[p].search(data, min(k, self.indices[p].n_samples_fit_))
     if len(scores_p)==0:
         continue
     scores_p, idx_p = scores_p[0], idx_p[0]
     scores.extend(scores_p)
     names.extend([self.ids[p][i] for i in idx_p])
 sorter = np.argsort(scores)
 scores = np.array(scores)[sorter].tolist()[:k]
 names = np.array(names)[sorter].tolist()[:k]
```

It works for `SciKitIndex`, but not for the other classes (it uses n_samples_fit_ of sklearn). But this is the idea, to take the min and then take the k most similar between all partitions.

**Comment by urigoren** [comment]
Thank you so much, solved in issue `0.0.37`
